name: Update Namnsdag Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"   # Kör varje morgon kl 05:00 svensk tid

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Pillow
        run: pip install Pillow

      - name: Install pytz
        run: pip install pytz

      - name: Run generator
        run: python3 generate.py

      - name: Commit updated image
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add namnsdag-2026.png
          git commit -m "Updated daily namnsdag image" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
